{% set name = "pydeck-carto" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98100ea7d4cef34f14947295ed5c59fda923c8453b60380824502d242ff01601

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydeck >=0.8.0
    - carto-auth >=0.1.0

test:
  imports:
    - pydeck_carto

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck-carto
  summary: Pydeck wrapper for use with CARTO
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pydeck-carto.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/blob/master/bindings/pydeck-carto

extra:
  recipe-maintainers:
    - Jesus89
