{% set name = "pydeck-carto" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 20156159f5a797db525836812d4108e237cb38985eaf43bba7d19344fa920fce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydeck >=0.8.0
    - carto-auth >=0.1.0

test:
  imports:
    - pydeck_carto

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck-carto
  summary: Pydeck wrapper for use with CARTO
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pydeck-carto.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/blob/master/bindings/pydeck-carto

extra:
  recipe-maintainers:
    - Jesus89
